In [76]:
# ------------------------------------------
# TAXA DE CONVERSAO BRL/USD : 4.40
# ------------------------------------------
PTAX = 4.40

In [77]:
# ------------------------------------------
# python version - documentation
# ------------------------------------------
!python --version

Python 3.7.13

In [78]:
# ------------------------------------------
# modulos pip
# ------------------------------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [79]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [80]:
# ------------------------------------------
# leitura das bases
# dataframe_D : moeda USD
# dataframe_R : moeda BRL
# ------------------------------------------
df_earnings_D = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/earnings-def.csv")
df_supply = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/supply-def.csv")
df_infos_gerais = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/infos-gerais-prov.csv")
df_attendance_rate = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/attendance-rate-def.csv")
df_incidentes_regras_rt = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/incidentes-regras-rt-def.csv")
df_ordens_done_cancel = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/ordens-done-cancel-def.csv")
df_product_return = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/product-return-prov.csv")
df_comp_defects = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/comp-defects-def.csv")
# df_criacao_contas_churn = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/criacao-contas-churn-sem-duplicados-prov.csv")
df_tempo_resolucao_modal = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/tempo-resolucao-modal-def.csv")

# Dataframe earnings

In [81]:
# ------------------------------------------
# DATAFRAME EARNINGS
# ------------------------------------------
# month: período mensal de ganhos do courier
# storekeeper_id: identificação do courier
# earnings: ganhos do courier no período
# tips: gorjetas do courier no período
# ------------------------------------------
df_earnings_D.head()

                  MONTH  STOREKEEPER_ID  EARNINGS   TIPS
0  2021-07-01T00:00:00Z           33161   1047.82  316.0
1  2021-07-01T00:00:00Z           33189    916.58  304.0
2  2021-07-01T00:00:00Z           33194   3076.38  552.0
3  2021-07-01T00:00:00Z           33207    160.42   44.0
4  2021-07-01T00:00:00Z           33213    268.63   59.0

In [82]:
MONTH = df_earnings_D["MONTH"]
mes = []
for m in MONTH:
  a = m.split("-")
  mes.append(int(a[1])) 


df_earnings_D["mes"] = mes

df_earnings_D["mes"].value_counts()
df_earnings_D.head()
df_earningsD_clean = df_earnings_D.drop(columns=['MONTH'])
df_earningsD_clean

        STOREKEEPER_ID  EARNINGS   TIPS  mes
0                33161   1047.82  316.0    7
1                33189    916.58  304.0    7
2                33194   3076.38  552.0    7
3                33207    160.42   44.0    7
4                33213    268.63   59.0    7
...                ...       ...    ...  ...
566094         1556676     32.14    3.0    7
566095         1556681     10.73    3.0    7
566096         1556689     19.50    2.0    7
566097         1556714     30.04    4.0    7
566098         1556765     28.25    2.0    7

[566099 rows x 4 columns]

In [83]:
#------------------------------------
# Número de linhas e colunas
#------------------------------------

df_earnings_D.shape

(566099, 5)

In [84]:
# ------------------------------------------
# periodo dos dados: julho-21 a julho-22
# ------------------------------------------
df_earnings_D["MONTH"].unique()

array(['2021-07-01T00:00:00Z', '2021-08-01T00:00:00Z',
       '2021-09-01T00:00:00Z', '2021-10-01T00:00:00Z',
       '2021-11-01T00:00:00Z', '2021-12-01T00:00:00Z',
       '2022-01-01T00:00:00Z', '2022-02-01T00:00:00Z',
       '2022-03-01T00:00:00Z', '2022-04-01T00:00:00Z',
       '2022-05-01T00:00:00Z', '2022-06-01T00:00:00Z',
       '2022-07-01T00:00:00Z'], dtype=object)